### ISSUE TITLE
D souns like D flat

### ISSUE THREAD

**Issue by viglov** [songscribe/SongScribe#2]
Hello,
I use Song Writer 1.20 and found that at some point D sounds like D 
flat. On the attached picture you can see what I am trying to play, but 
D does not sound like D but like D flat.
If i start new document and enter just D and D flat it plays them 
correctly. But if I enter other notes the sound of D become same as D
flat.
![capture](https://cloud.githubusercontent.com/assets/13346023/8693159/abd3c918-2add-11e5-8ce1-25fb5e4429d3.JPG)

**Comment by kavai77** [comment]
Fixed with commit: https://github.com/songscribe/SongScribe/commit/20d6d3c20059a8368927db919572677292ca581e
